# Generated by Django 3.1 on 2020-08-19 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20200819_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='aporte_arl',
            field=models.FloatField(default=0, verbose_name='Porcentaje Aportes de Pension'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 21, 25, 56, 947365, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 21, 25, 56, 946367, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='fac_especialista',
            name='fechafac_esp',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 21, 25, 56, 949359, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
