# Generated by Django 3.1 on 2020-08-19 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20200819_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='aporte_arl',
            field=models.FloatField(default=0, verbose_name='Porcentaje Aportes de ARL'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 21, 33, 28, 530604, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 21, 33, 28, 530604, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='fac_especialista',
            name='fechafac_esp',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 21, 33, 28, 530604, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
