# Generated by Django 3.1 on 2020-12-15 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0064_auto_20201215_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centro_actividad',
            name='especialista',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 12, 15, 14, 18, 37, 547943, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2020, 12, 15, 14, 18, 37, 547943, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='fac_especialista',
            name='fechafac_esp',
            field=models.DateField(default=datetime.datetime(2020, 12, 15, 14, 18, 37, 547943, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
