# Generated by Django 3.1 on 2020-12-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0065_auto_20201214_1356'),
        ('facturacion', '0067_auto_20201215_0935'),
    ]

    operations = [
    ]
