# Generated by Django 3.1 on 2021-02-16 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0068_merge_20201215_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnvioMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=15, verbose_name='Numero de Factura')),
                ('fecha_envio', models.DateTimeField(verbose_name='Fecha de Envio')),
                ('Estado', models.CharField(max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 13, 30, 38, 336584, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 13, 30, 38, 335586, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='fac_especialista',
            name='fechafac_esp',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 13, 30, 38, 338578, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
