# Generated by Django 3.1 on 2021-02-16 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0069_auto_20210216_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroenviomail',
            name='ruta',
            field=models.CharField(max_length=300, null=True, verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 14, 24, 25, 968026, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 14, 24, 25, 968026, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='fac_especialista',
            name='fechafac_esp',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 14, 24, 25, 971040, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
