# Generated by Django 3.1 on 2021-02-16 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0070_auto_20210216_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroenviomail',
            name='archivo',
            field=models.CharField(default='null', max_length=100, verbose_name='Archivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 15, 13, 17, 322374, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 15, 13, 17, 322374, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='fac_especialista',
            name='fechafac_esp',
            field=models.DateField(default=datetime.datetime(2021, 2, 16, 15, 13, 17, 324369, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
