# Generated by Django 3.1 on 2021-02-27 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0074_auto_20210227_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 2, 27, 17, 26, 1, 298217, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2021, 2, 27, 17, 26, 1, 297220, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='fac_especialista',
            name='fechafac_esp',
            field=models.DateField(default=datetime.datetime(2021, 2, 27, 17, 26, 1, 300212, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
