# Generated by Django 3.1 on 2021-03-01 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0076_auto_20210227_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 14, 42, 3, 475870, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 14, 42, 3, 475870, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='fac_especialista',
            name='fechafac_esp',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 14, 42, 3, 478861, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
