# Generated by Django 3.1 on 2020-08-19 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concepto_canasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_canasta', models.CharField(max_length=85, null=True, verbose_name='Concepto de la Canasta')),
            ],
            options={
                'ordering': ['nombre_canasta'],
            },
        ),
        migrations.CreateModel(
            name='concepto_honorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concep_hon', models.CharField(max_length=30, null=True, verbose_name='Nombre del Concepto')),
            ],
            options={
                'ordering': ['nombre_concep_hon'],
            },
        ),
        migrations.CreateModel(
            name='concepto_salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concep_sal', models.CharField(max_length=30, null=True, verbose_name='Concepto')),
            ],
            options={
                'ordering': ['nombre_concep_sal'],
            },
        ),
        migrations.CreateModel(
            name='constante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss_adicional', models.FloatField(null=True, verbose_name='Porcentaje Ganancia')),
                ('valor_uvt', models.FloatField(default=0, null=True, verbose_name='Valor UVT Especialistas')),
                ('smdlv', models.FloatField(default=0, null=True, verbose_name='Salaraio Minimo Diario L.V.')),
            ],
            options={
                'ordering': ['iss_adicional'],
            },
        ),
        migrations.CreateModel(
            name='nombre_canasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_canasta', models.CharField(max_length=85, null=True, verbose_name='Nombre de la Canasta')),
            ],
            options={
                'ordering': ['nombre_canasta'],
            },
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_act', models.CharField(max_length=20, null=True, verbose_name='lugar del proceso donde se ubica')),
            ],
            options={
                'ordering': ['nombre_act'],
            },
        ),
        migrations.CreateModel(
            name='procedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('nombre_proc', models.CharField(max_length=190, null=True, verbose_name='Nombre del Procedimiento')),
                ('duracion_proc', models.FloatField(null=True, verbose_name='Duración en minutos')),
                ('uvr', models.FloatField(blank=True, default=0, null=True, verbose_name='UVR')),
                ('dias_estancia', models.IntegerField(default=0, null=True, verbose_name='Días Estancia')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_estancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_est', models.CharField(max_length=60, null=True, verbose_name='Tipo de Estancia')),
                ('numero_camas', models.IntegerField(default=0, null=True, verbose_name='Número de Camas')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_proc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_proc', models.CharField(max_length=80, null=True, verbose_name='Nombre de la Especialidad')),
            ],
            options={
                'ordering': ['nombre_tipo_proc'],
            },
        ),
        migrations.CreateModel(
            name='salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField(null=True, verbose_name='Costo')),
                ('concepto_salario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.concepto_salario', verbose_name='Concepto')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.position', verbose_name='Ubicación Concepto')),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.procedimiento', verbose_name='Nombre del Procedimiento')),
                ('tipo_proc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Tipo Procedimiento')),
            ],
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='tipo_proc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Especialidad'),
        ),
        migrations.CreateModel(
            name='honorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Información')),
                ('costo', models.FloatField(blank=True, default=0, null=True, verbose_name='Costo no Paramertrizado')),
                ('concepto_honorario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.concepto_honorario', verbose_name='Concepto')),
                ('nombre_canasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.nombre_canasta', verbose_name='Canasta')),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.procedimiento', verbose_name='Nombre del Procedimiento')),
                ('tipo_proc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='estancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_estancia', models.CharField(max_length=40, null=True, verbose_name='Concepto Estancia')),
                ('valor_concepto', models.FloatField(default=0, null=True, verbose_name='Valor día')),
                ('dividir_por_cama', models.BooleanField(default=True, verbose_name='¿Se divide entre el número de camas ?')),
                ('tipo_estancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_estancia', verbose_name='Tipo de Estancia')),
            ],
        ),
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganancia', models.FloatField(default=0, verbose_name='Ganancia')),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.procedimiento', verbose_name='Nombre del Procedimiento')),
                ('tipo_proc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Tipo Procedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='canasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=120, null=True, verbose_name='Nombre Insumo')),
                ('presentacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Presentación')),
                ('cantidad', models.FloatField(default=1, null=True, verbose_name='Cantidad')),
                ('costo_und', models.FloatField(null=True, verbose_name='Costo Unitario')),
                ('costo_tot', models.FloatField(default=0, null=True, verbose_name='Costo Subtotal')),
                ('concepto_canasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.concepto_canasta', verbose_name='Concepto')),
                ('nombre_canasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.nombre_canasta', verbose_name='Nombre de la Canasta')),
                ('position', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.position', verbose_name='Ubicación')),
            ],
        ),
    ]
