# Generated by Django 3.1 on 2020-10-14 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='canasta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.nombre_canasta', verbose_name='Canasta'),
        ),
    ]
