# Generated by Django 3.1 on 2020-10-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0003_auto_20201014_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='nombre_act',
            field=models.CharField(max_length=20, null=True, verbose_name='Nombre de la Actividad'),
        ),
    ]
