# Generated by Django 3.1 on 2020-10-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso_solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=60, verbose_name='Escriba el nombre del Area Funcional')),
            ],
        ),
    ]
