# Generated by Django 3.1 on 2020-10-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_proceso_solicitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('description', models.TextField(verbose_name='Descripción del Articulo o Activo')),
                ('ref', models.CharField(max_length=20, verbose_name='Referencia')),
                ('justificacion', models.TextField(verbose_name='Justificación')),
                ('obs', models.TextField(blank=True, verbose_name='Observación')),
                ('fecha_solici', models.DateTimeField(verbose_name='Fecha de Solicitud')),
                ('fecha_aprob', models.DateTimeField(verbose_name='Fecha de Aprobación')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.estado', verbose_name='Estado')),
                ('proceso_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.proceso_solicitante', verbose_name='Area Funcional que representa la Necesidad')),
                ('und', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.unidadmedida', verbose_name='Unidad de Medida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.usuario', verbose_name='Cargo')),
            ],
        ),
    ]
