# Generated by Django 3.1 on 2020-10-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0005_auto_20201005_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='proceso_solicitante',
        ),
    ]
