# Generated by Django 3.1 on 2020-10-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0006_remove_solicitud_proceso_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='proceso_solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.proceso_solicitante', verbose_name='Area Funcional que representa la Necesidad'),
        ),
    ]
