# Generated by Django 3.1 on 2020-10-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0007_usuario_proceso_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='area',
        ),
    ]
