# Generated by Django 3.1 on 2020-10-05 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0008_remove_usuario_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solici',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 16, 10, 21, 720685, tzinfo=utc), verbose_name='Fecha de Solicitud'),
        ),
    ]
