# Generated by Django 3.1 on 2020-10-05 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0009_auto_20201005_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solici',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 11, 29, 32, 951009), verbose_name='Fecha de Solicitud'),
        ),
    ]
