# Generated by Django 3.1 on 2020-10-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0010_auto_20201005_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solici',
            field=models.DateTimeField(verbose_name='Fecha de Solicitud'),
        ),
    ]
