# Generated by Django 3.1 on 2020-10-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0011_auto_20201005_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='estado',
        ),
    ]
