# Generated by Django 3.1 on 2020-10-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0012_remove_solicitud_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='und',
            new_name='unidadMedida',
        ),
    ]
