# Generated by Django 3.1 on 2020-10-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0013_auto_20201027_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Gerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud', verbose_name='Solicitud')),
            ],
        ),
    ]
