# Generated by Django 3.1 on 2020-10-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0014_estado_gerencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_gerencia',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud', verbose_name='Solicitud'),
        ),
    ]
