# Generated by Django 3.1 on 2020-10-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0016_auto_20201027_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado_Gerencia',
            new_name='Estado_Principal',
        ),
    ]
