# Generated by Django 3.1 on 2020-10-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0017_auto_20201027_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Secundario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Ejecución', 'Ejecución'), ('Entregado', 'Entregado')], default='Ejecución', max_length=12, verbose_name='Solicitud')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('quien_aprobo', models.CharField(max_length=60, null=True, verbose_name='Usuario que Aprobó o Denegó')),
                ('fecha_aprob', models.DateTimeField(null=True, verbose_name='Fecha de Aprobación')),
            ],
        ),
    ]
