# Generated by Django 3.1 on 2020-10-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0018_estado_secundario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_secundario',
            name='estado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Ejecución', 'Ejecución'), ('Entregado', 'Entregado')], default='Ejecución', max_length=12, verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='estado_secundario',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud', verbose_name='Solicitud'),
        ),
    ]
