# Generated by Django 3.1 on 2020-10-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0019_auto_20201028_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_principal',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Denegado', 'Denegado')], default='Pendiente', max_length=12, verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='estado_secundario',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Gestionado', 'Gestionado')], default='Pendiente', max_length=12, verbose_name='Solicitud'),
        ),
    ]
