# Generated by Django 3.1 on 2020-11-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0022_auto_20201109_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_principal',
            name='obs',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='estado_secundario',
            name='obs',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
    ]
